name: Build and Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: macos-14
    env:
      DEVELOPER_DIR: /Applications/Xcode_15.3.app/Contents/Developer
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Select Xcode
      run: sudo xcode-select -s /Applications/Xcode_15.3.app
      
    - name: Build
      run: |
        xcodebuild clean build -project force-observations.xcodeproj -scheme force-observations -destination 'platform=macOS' | xcpretty
        
    - name: Test
      run: |
        xcodebuild test -project force-observations.xcodeproj -scheme force-observations -destination 'platform=macOS' | xcpretty 